[workspace]
members = [
    "zkrpc",
    "da-layer",
    "config",
    "logger",
    "types",
    "pox",
    "zkt",
    "util", "pom",
]

resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = []
description = "zk rpc"
