//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "terminal")]
pub struct Model {
    pub mac: String,
    #[sea_orm(column_type = "Float")]
    pub y: f32,
    #[sea_orm(column_type = "Float")]
    pub x: f32,
    pub address: String,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::terminal_track::Entity")]
    TerminalTrack,
}

impl Related<super::terminal_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TerminalTrack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
