//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "terminal_track")]
pub struct Model {
    pub block_number: i32,
    pub satellite_mac: String,
    pub terminal_mac: String,
    #[sea_orm(column_type = "Float")]
    pub signal_strength: f32,
    pub net_bandwidth: i32,
    pub net_traffic: i32,
    pub connect_time: i64,
    pub disconnect_time: Option<i64>,
    pub net_latency: i32,
    pub droped_ip_packets: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
