log:
  format: OneLine
  log_dir: logs
  log_level: trace
  show_source_location: true
  show_with_target: true
  show_thread_ids: false
  show_thread_names: false
  write_to_file: false
  rotation: daily
  show_span_duration: false
rpc:
  rpc_port: 15937
  rpc_host: 127.0.0.1
  client_host: 127.0.0.1
  timeout: 60
da_layer: !MockDaLayerConfig
  host: localhost
  port: 3306
  user: root
  password: root
  database: test
  sqlx_log_level_filter: debug
pox:
  rayon_num_threads: 0
  coordinate_precision_bigint: 3
  rspr_precision_bigint: 4
  penalty:
    max_diff: '10'
  kernel:
    kernel_type: GaussianTaylor
    gaussian:
      sigma: '500'
      vanilla:
        use_coef: false
      taylor:
        max_order: 20
        sigma_range: '3.0'
    quadratic:
      max_dis_sqr: '10000'
  pod_max_value: '-100'
compressor:
  brotli:
    quality: 11
    lgwin: 20
    buffer_size: 4096
  flate2:
    level: 9
    flate2_type: Zlib
