log:
  log_dir: logs
  log_level: trace
  show_file_path: false
  show_line_number: false
  show_with_target: true
  write_to_file: false
  rotation: daily
rpc:
  rpc_port: 15937
  rpc_host: 127.0.0.1
da_layer: !MockDaLayerConfig
  host: localhost
  port: 3306
  user: root
  password: root
  database: test
pox:
  cooridnate_precision_bigint: 3
  rspr_precision_bigint: 4
  sigma_range: '3.0'
  sigma: '40000'
